### ISSUE TITLE
Add Custom Favicon

### ISSUE THREAD

**Issue by imsaptarshi** [Mikael-R/ChatJS#5]
Can I add a custom favicon to your app?..as It doesn't has one

**Comment by Mikael-R** [comment]
Yes it would be great

**Comment by LaxmanJonchhen12** [comment]
is the favicon already place in the chat app

**Comment by Mikael-R** [comment]
#### Maybe that helps

- [Flaticon](https://www.flaticon.com/)
- [Icons8](https://icons8.com/)
- [Icon Finder](https://www.iconfinder.com/)
- [Material Design](https://material.io/icons/)
- [Freepik](https://www.freepik.com/popular-icons/)

**Comment by saptarshibasu15** [comment]
#9

**Comment by imsaptarshi** [comment]
#9
