### ISSUE TITLE
Create readme file

### ISSUE THREAD

**Issue by Mikael-R** [Mikael-R/ChatJS#7]
Generate readme file using [readme-template-generator](https://npmjs.com/readme-template-generator)

**Comment by LaxmanJonchhen12** [comment]
hello i will make an readme file

**Comment by Mikael-R** [comment]
It was done on [this commit](https://github.com/Mikael-R/chat-js/commit/b2b0bc1c52d736effb6afc908227ba1bafa23a3e)
